README.md
Add a note to the `Slack App Route` doc: one must add a bot user to the channel, otherwise all attempts to post a message will throw `not_in_channel` error.
=> Add a note to the `Slack App Route` doc

README.md
resolve #8
Added a link URL to the "create slack app" anchor.  
This resolves the Issues in #8.
=> docs: fix create slack app link

README.md
Fix a small typo in the link to the license file.
=> README.md: fix typo in link name

example-workflows/Bot token post to channel/JSONTextPayload.yml, example-workflows/Bot token post to channel/customJSONPayload.yml, index.js
The goals of this PR is to enable BotToken users to leverage the payload to pass json to a bot and resolves #18
=> Fix #18 - Enable passing JSON payload to Slack App Route

.github/workflows/publish.yaml
As identified in https://github.com/slackapi/slack-github-action/issues/16, there are no automated builds or releases being done.  This added workflow will build on release and update the associated major/minor tracking tags - if you do a `v1.16.0` release; it will build, update the `dist/index.json` to a new commit, then update the release tag as well as the tracking tags `v1` and `v1.16` automatically.
It will still require someone manually making a new version release after a merge to master. This could further be automated to use a merge commit message.
=> Adding automated build & tag update on release

.github/maintainers_guide.md, README.md, package.json
Updating README and maintainer guide. Also updating version in package.json to match latest released version.
=> Updating maintainer and README documentation

README.md
As shown in #40 - Since we don't support usernames (rather user ids), this tweak clarifies the usage instructions.
=> clarify user id vs name

.github/resources/payload-notification.json, .github/workflows/main.yml, README.md, example-workflows/Workflow_Builder/JSON_payload_from_file.yml, example-workflows/payloads/example.json, src/slack-send.js, test/resources/invalid-payload.json, test/resources/valid-payload.json, test/slack-send-test.js
Fixes: https://github.com/slackapi/slack-github-action/issues/43
Increase code coverage.
Updated Readme to have the new input type.
Added example for the new input type usage.
Describe the goal of this PR. Mention any related Issue numbers.
=> [#43] Add payload file path to enhance the github action.

package-lock.json, package.json, src/slack-send.js, test/resources/valid-payload.json, test/slack-send-test.js
Describe the goal of this PR. Mention any related Issue numbers.
Fixes #51 
Added Code for accessing github context variables in payload json file
Updated Valid TestCase
=> fixed #51 for env variables in payload json file

.github/workflows/main.yml, action.yml, src/slack-send.js, test/slack-send-test.js
Fixes #73 by adding `thread_ts` as an output when using a botToken. This is useful for threading.
=> #73 added thread-ts as an output

README.md, src/slack-send.js, test/slack-send-test.js
#75 
- `outputs.time` was not what I need. Added `outputs.ts`
- added `update-ts` option which calls `chat.update` api 
```yml
- id: slack
uses: slackapi/slack-github-action@v1.18.0
with:
channel-id: "#channel"
payload: |
{
"attachments": [
{
"pretext": "Deployment started",
"color": "dbab09",
"fields": [
{
"title": "Status",
"short": true,
"value": "In Progress"
}
]
}
]
}
env:
SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
- uses: slackapi/slack-github-action@v1.18.0
with:
channel-id: "#channel"
update-ts: ${{ steps.slack.outputs.ts }}
payload: |
{
"attachments": [
{
"pretext": "Deployment finished",
"color": "28a745",
"fields": [
{
"title": "Status",
"short": true,
"value": "Completed"
}
]
}
]
}
env:
SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
```
=> Add support to update messages #75

README.md, src/slack-send.js, test/slack-send-test.js
Adds support for comma-separated channel ID's.
Closes #118
=> feat(message): support multiple channel IDs

action.yml, package-lock.json, package.json
Bumps node12 to node16. Also suggesting at least node 16 for install. Node 12 is EOL.
=> Bump node from 12 to 16

package-lock.json, package.json, src/slack-send.js, test/slack-send-test.js
Add an https-proxy-agent when HTTP proxy is used by action consumer and webhook uses HTTPS.
Issue: https://github.com/slackapi/slack-github-action/issues/131
This pull request resolves #131
=> Use https proxy agent

.github/maintainers_guide.md
Update maintainer's guide to include instructions on running testing before pushing up commits directly to `main`. Also standardized bullet point punctuation in the maintainer's guide.
=> Add in testing instructions for maintainer's guide and standardize bullet point punctuation

src/slack-send.js
=> Added checks for bot token and webhook url length

action.yml, src/slack-send.js
We would like to use channel name for posting new messages instead of channel id. From the response we can get channel ID, export it as output parameter and use it later for updating messages or posting to threads the same way as we use ts or thread_ts.
Workaround/solution for #136.
=> Add channel_id output parameter

README.md, example-workflows/Technique_2_Slack_App/JSON_payload.yml
This pull request updates the docs and examples for Technique 2 to use [GitHub Actions Context](https://docs.github.com/en/actions/learn-github-actions/contexts) instead of the `values` property.
This fixes the error `Unexpected value 'values'` that was reported in #171 and matches the approach documented in the `README.md`.
You can find a working example of this update in the repo: [mwbrooks/slack-github-action-example](https://github.com/mwbrooks/slack-github-action-example)
=> [#171] Update Technique 2 to use Actions context instead of values property

README.md
=> Update README.md with variable usage and links to example workflows.

.github/workflows/main.yml
With testing https://github.com/slackapi/slack-github-action/pull/205, in the PR https://github.com/slackapi/slack-github-action/pull/206 to make sure the integration tests run, it was determined that the `toJSON()` in the payload integration test doesn't seem to work to parse the body of a given PR if it contains characters that need to be escaped within a string (example error output can be found in [this test run](https://github.com/slackapi/slack-github-action/actions/runs/5134722650/jobs/9239300076)).
However, there is a workaround for this in which bash automatically escapes invalid characters in env variables ([see this issue for more info](https://github.com/actions/runner/issues/1656)). This PR adds in this workaround so that all future PRs will successfully parse as JSON, …
=> Update payload integration test to escape invalid characters

README.md
The previously docs described "Technique 1" as "the recommended way to use this action", but that doesn't make sense given it doesn't support any text or message formatting (cf. https://github.com/slackapi/slack-github-action/issues/192#issuecomment-1641400917). This attempts to make that limitation clearer, cc @seratch.
=> README: clarify limitations to workflow builder approach

.github/maintainers_guide.md, .github/workflows/local/.env.example, .github/workflows/local/.gitignore, .github/workflows/local/README.md, .github/workflows/local/event.json, .github/workflows/local/local.yml, package.json
This PR introduces instructions for developing with a local version of the action to improve the development experience. No longer are pushes and tags to a remote branch necessary.
These changes allow custom configurations to be made to the event payloads to test various cases, and different techniques can be tried with changes to the `local.yml` file.
At the moment only a simple `payload` is provided to mock [Technique 1](https://github.com/slackapi/slack-github-action#technique-1-slack-workflow-builder). I think this is alright to start as more events could be added over time, or experiments can just be performed locally.
Open to any thoughts on this!
=> Add instructions for developing with a local version of the action

.github/maintainers_guide.md, .github/workflows/main.yml
This PR attempts to pass secrets to integration tests for PRs opened from a fork. Fixes #251.
PRs not opened by a `COLLABORATOR` will initially fail because secrets "are not passed to workflows that are triggered by a pull request from a fork" but checking out the `head.sha` on a re-run is [an apparent workaround for this](https://michaelheap.com/access-secrets-from-forks/) and workflows can be re-run by a maintainer!
- Other options for `author_associations` include [`MEMBER`](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) which might work better for the check in `access_check`. I think a re-run will pass this check in any case though 🤔
=> Pass secrets to approved workflow jobs

action.yml, package.json
This PR bumps the version of Node to [the active LTS](https://nodejs.org/en/about/previous-releases#release-schedule) (Node 20) to remain current with packages that have dropped support for Node 16.
The updated runtime doesn't seem to be a breaking change as the action is [executed using this runtime](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) without being specified by the calling workflow, but willing to adjust the semver if needed!
=> build(node): bump the runtime version to node 20

.github/workflows/main.yml
Without specifying the ref to check out, `checkout@v4` will check out the default branch, which is `main`. 😑 not helpful
=> Unit tests in GitHub CI should test the PR/branch

.github/workflows/main.yml
This PR requires the `access_check` step to pass before running `unit_tests` to prevent unexpected changes from branched PRs happening in actions.
A note about the `access_check` is also added to the workflow file.
=> ci(security): require access checks to pass before running unit tests

.github/workflows/main.yml
This PR updates the `access_check` to check that the event is a a `pull_request_target` instead of a `pull_request`.
=> ci(security): check for pull_request_target events in the access check

.github/workflows/main.yml
This PR updates the integration tests to use [a `staging` environment](https://github.com/slackapi/slack-github-action/settings/environments/2483877568/edit) 🔐 for workflow jobs. This staging environment has an access check that requires approval from @slackapi/developer-tools and then grants access to environment secrets when running the jobs.
The previous `pull_request_target` `access_check` checks were reverted here but a note remains in the [maintainer's guide](https://github.com/slackapi/slack-github-action/blob/main/.github/maintainers_guide.md#checks-on-prs).
Using environment might act as a "deployment" which will appear on the repo home page. I suggest we hide this since the `staging` environment is only used in testing.
- …
=> ci(test): collect environment secrets from a prepared staging environment

README.md
This PR adjust a missing whitespace in README.
Now all env vars have the same pattern `${{ value }}` instead of `${{ value}}`.
=> docs(readme): adjust whitespace in env assignment

.github/workflows/main.yml, .gitignore, README.md, package.json
Describe the goal of this PR. Mention any related Issue numbers.
=> Add codecov coverage uploading

README.md, test/slack-send-test.js
This resolved #187 
This PR adds documentation describing how to reply to an existing message and a unit test to ensure the behavior is maintained
=> doc: how to reply to a message

.github/workflows/main.yml
This PR makes all tests - both unit and integration - run in a single sequential environment to reduce noise on PRs and make parsing tests a bit easier.
https://github.com/zimeg/slack-github-action/actions/runs/9275691157/job/25522352820
=> ci(test): run integration tests in a single sequential environment

README.md, action.yml, src/slack-send.js, test/slack-send-test.js
Fixes #280.
The default key delimiter when flattening payloads is a period, which is not allowed in Slack workflow variable keys. This makes the `slack-send` action unusable with Slack workflows/incoming webhooks if the payload contains nested keys as there is no way to access those keys (as far as I can tell).
For example if I want to include workflow metadata from GitHub in my payload with `${{ toJson(github) }}`, all nested keys are inaccessible, and if I want to compose this with other custom variables by nesting the serialized `github` values like `"github": ${{ toJson(github) }}, "some-key": "some-value"`, then all of the GitHub metadata is inaccessible because it's all prefixed with `github.` and can't be entered as a variable key in a Slack workflow. Underscores and hyphens are …
=> Make payload delimiter configurable

package-lock.json, package.json
This PR bumps the minimum version of axios to 1.7.5 to address a CVE - see [Axios 1.7.4 release notes](https://github.com/axios/axios/releases/tag/v1.7.4) for more information.
Also here is a bump to `@slack/web-api` that has [a similar patch update](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fweb-api%407.3.4) 🚀
=> chore(deps): bump axios to 1.7.5 to address CVE-2024-39338

.github/workflows/main.yml
This PR adds the 🏥 [slackapi/slack-health-score](https://github.com/slackapi/slack-health-score) to this action as part of regular check ups!
Hopes to fix strangeness that happens when [adding this action another PR](https://github.com/slackapi/slack-github-action/actions/runs/11131514332/job/30933247951?pr=333#step:31:11). I'm hoping this fixes missing commits, but am unsure if this is a real fix 😳 
Please forgive the misuse of a `diff` but these are the errors shown in the other run:
```diff
> Run slackapi/slack-health-score@v0.1.1
with:
codecov_token: ***
github_token: ***
extension: js
env:
EVENT_URL: https://github.com/slackapi/slack-github-action/pull/333
Using SHA: 7c719bb2a1a67ec8972d7edd09a24c26856f306f
Pinging codecov API for coverage data...
- Error: Failed to retrieve codecov …
```
=> ci: include the slack health score as part of ci tests

README.md
While implementing functionality as per the documentation, the channel parameter did not work as expected. Upon reviewing the official reference [Upload a File - Slack API Documentation](https://tools.slack.dev/node-slack-sdk/web-api/#upload-a-file), I noticed that the correct parameter is channel_id. After making this change, the functionality worked as intended.
This PR proposes a fix to update the documentation to reflect the correct parameter, ensuring that other users do not encounter the same issue.
=> docs: fix incorrect parameter name in uploadV2 (channel -> channel_id)

src/config.js, src/send.js, test/config.spec.js, test/index.spec.js, test/send.spec.js
This PR allows both environment variables `SLACK_TOKEN` and `SLACK_WEBHOOK_URL` to exist in a workflow without causing steps to error due to an undefined technique! Fixes #373.
Add the following to the workflow in `develop.yml` before running with `npm run dev`:
```diff
+   env:
+     SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
runs-on: ubuntu-latest
```
This should error before the change is applied but not after!
=> fix: avoid erroring if conflicting techniques are set from environment variables

.github/workflows/develop.yml, .github/workflows/publish.yml, .github/workflows/test.yml, package.json
Small update to avoid persisting `git` credentials between steps of an action, and reduces the permissions of each `$GITHUB_TOKEN` to the minimum required.
This makes no changes to how the [`$GITHUB_TOKEN` can be accessed](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret) from the workflow!
These changes were tested on a forked `main`:
- `develop.yml`: No changes!
- `publish.yml`: https://github.com/zimeg/slack-github-action/actions/runs/12321675869/job/34394241333
- `test.yml`: https://github.com/zimeg/slack-github-action/actions/runs/12321990320/job/34394566023
=> ci: reduce the permissions for github actions jobs

package-lock.json, package.json, src/client.js, src/config.js, src/logger.js, test/client.spec.js, test/index.spec.js, test/logger.spec.js
This PR refactors the `logger` setup used for `@slack/web-api` to a standalone file to test that the configured action inputs are used when constructing the `WebClient` 👾 
Hopefully no changes to functionality, but an improvement to testing for following changes!
=> refactor: setup the logger using core configuration values

README.md
This PR adds a migration guide to the `README` and a "table of contents" to find fast links between section headers 👾 ✨ 
Following #398!
🔗 https://github.com/slackapi/slack-github-action/tree/docs-migration-guide
=> docs: include versioning details and migration guides in the readme

package-lock.json
This PR bumps the depended upon `cross-spawn` package to the latest 7.0.6 at the recommendation of `npm audit` 🫡 
```
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
The code changes were generated with `npm audit fix`!
=> build(deps): bump cross-spawn from 7.0.3 to 7.0.6

docs/sending-variables.md, docs/slack-github-action.md
The homepage should be a home page not a home and topic page. now this topic is on a page.
We're immediately testing the worst edge case -- the resulting PR in the docusaurus repo will need to be modified to add the page to `sidebar.js`. Not too cumbersome to do via web client though
=> docs: pulls out variables into separate page

docs/additional-configurations.md, docs/sending-techniques/sending-data-slack-api-method/sending-data-slack-api-method.md, docs/sending-techniques/sending-data-slack-incoming-webhook/sending-data-slack-incoming-webhook.md, docs/sending-techniques/sending-data-webhook-slack-workflow/sending-data-webhook-slack-workflow.md, docs/sending-techniques/sending-techniques.md, example-workflows/Technique_1_Slack_Workflow_Builder/announcements.gha.yml, example-workflows/Technique_1_Slack_Workflow_Builder/builds.gha.yml, example-workflows/Technique_1_Slack_Workflow_Builder/topic.gha.yml, example-workflows/Technique_2_Slack_API_Method/author.yml, example-workflows/Technique_2_Slack_API_Method/invite.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/blocks.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/saved.gha.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/text.yml, package-lock.json, package.json
This PR tags the latest changes on `main` as version 2.1.0. This includes the milestones:
- `2.1`: https://github.com/slackapi/slack-github-action/milestone/17
- `2.0.1`: https://github.com/slackapi/slack-github-action/milestone/16
Which will soon be moved to `2.1`! Full changelog: https://github.com/slackapi/slack-github-action/compare/v2.0.0...ab965e58bdca6c60639a701a79d306baf0cefd65
- Hoping to follow up with a [`MAINTAINERS_GUIDE.md`](https://github.com/slackapi/slack-github-action/blob/main/.github/maintainers_guide.md#releasing) change to include changes to `package-lock.json` and related labels 🙏 ✨
=> chore(release): tag version 2.1.0

.github/workflows/develop.yml, .github/workflows/publish.yml, .github/workflows/sync-docs.yml, .github/workflows/test.yml
This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾 
While not so simple to bump ourselves, the kind @dependabot can help keep these hashes updated with the changes of https://github.com/dependabot/dependabot-core/pull/5951 having landed 🤖 ✨
A similar audit can be performed with the `zizmor` tool:
```sh
$ zizmor .
...
No findings to report. Good job! (1 ignored, 4 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
Most changes I hope are repetitive, but I will comment on the more significant ones! FWIW the `develop` and `test` workflow continue to work with these …
=> ci: pin action hashes and escape variables with minimum permission

docs/sending-techniques/sending-data-slack-api-method/sending-data-slack-api-method.md
This pull request closes https://github.com/slackapi/slack-github-action/issues/446 by updating the docs to use `<!channel>` instead of `<@channel>` when mentioning the channel. [See special formatting documentation](https://api.slack.com/reference/surfaces/formatting#special-mentions).
Big thanks to @jacklu97 for reporting this issue! 🙇🏻
=> docs: fix channel mention formatting

.github/maintainers_guide.md, .github/workflows/publish.yml
This PR creates separate release branches for tagged releases from the changes on `main` to avoid appearances of the confusing "imposter commit". Fixes #444.
Release candidates with these attempted changes can be found from a fork:
- https://github.com/zimeg/slack-github-action/releases/tag/v2.1.1-rc.6
Notice that https://github.com/zimeg/slack-github-action/commit/9dd078e82245b6abf6ecca61735ab0d2699bc890 is part of the [`v2.1.1-rc.6`](https://github.com/zimeg/slack-github-action/releases/tag/v2.1.1-rc.6) release branch while an earlier commit for [`v2.1.1-rc.1`](https://github.com/zimeg/slack-github-action/releases/tag/v2.1.1-rc.1) is shown as https://github.com/zimeg/slack-github-action/commit/91855720aaee2e23bf81dae3512204a371ca1609 and contains the warning:
> ⚠️ This commit does not …
=> build: create separate release branches for tagged releases on publish

docs/additional-configurations.md, docs/sending-techniques/sending-data-slack-api-method/sending-data-slack-api-method.md, docs/sending-techniques/sending-data-slack-incoming-webhook/sending-data-slack-incoming-webhook.md, docs/sending-techniques/sending-data-webhook-slack-workflow/sending-data-webhook-slack-workflow.md, docs/sending-techniques/sending-techniques.md, example-workflows/Technique_1_Slack_Workflow_Builder/announcements.gha.yml, example-workflows/Technique_1_Slack_Workflow_Builder/builds.gha.yml, example-workflows/Technique_1_Slack_Workflow_Builder/topic.gha.yml, example-workflows/Technique_2_Slack_API_Method/author.yml, example-workflows/Technique_2_Slack_API_Method/invite.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/blocks.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/saved.gha.yml, example-workflows/Technique_3_Slack_Incoming_Webhook/text.yml, package-lock.json, package.json
This PR tags the latest changes on `main` as version `2.1.1` - these updates were made using the scripts of #439!
Milestone: https://github.com/slackapi/slack-github-action/milestone/18
=> chore(release): tag version 2.1.1
